---
apiVersion: velero.io/v1
kind: Restore
metadata:
  name: nginx-backup
  namespace: velero
spec:
  backupName: nginx-backup
  excludedResources:
  - node
  - events
  - events.events.k8s.io
  - backups.velero.io
  - restores.velero.io
  includedNamespaces:
  - '*'
