---
- name: Create Nginx application
  k8s:
    state: "{{ state }}"
    definition: "{{ lookup('file', 'base.yaml')}}"

- name: Wait 2 minutes for nginx deployment
  k8s_facts:
    api_version: "apps/v1"
    kind: "Deployment"
    namespace: "nginx-example"
    label_selectors:
      - "app = nginx"
  register: deploy
  until: deploy
         and (deploy.resources | length > 0)
         and (deploy.resources[0].get("status", {}).get("replicas",-1) == deploy.resources[0].get("status", {}).get("availableReplicas", -2))

- name: Create velero backup of nginx
  k8s:
    state : "{{ state }}"
    definition: "{{ lookup('file', 'create-backup.yml')}}"

- name: Wait 1 minute for backup to complete
  k8s_facts:
    api_version: "velero.io/v1"
    kind: "Backup"
    namespace: "velero"
  register: backup
  until: backup
         and (backup.resources | length > 0)
         and (backup.resources[0].get("status", {}).get("phase", 0) == "Completed")
  retries: 10
  delay: 5

