---
apiVersion: velero.io/v1
kind: Backup
metadata:
  name: nginx-backup
  namespace: velero
spec:
  labelSelector:
    matchLabels:
      app: nginx
  storageLocation: default
  ttl: 720h0m0s
  includedNamespaces:
  - '*'
